# Generated by Django 4.2.13 on 2024-05-26 02:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='DivisionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name_plural': 'DivisionCategories',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='ResponsibilityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'indexes': [models.Index(fields=['name'], name='respCategory_name_idx')],
            },
        ),
        migrations.CreateModel(
            name='PartCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name_plural': 'PartCategories',
                'indexes': [models.Index(fields=['name'], name='partCategory_name_idx')],
            },
        ),
        migrations.CreateModel(
            name='MajorQualityCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('進捗', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('市場発生', models.BooleanField(default=False, null=True)),
                ('再発防止', models.BooleanField(default=False, null=True)),
                ('出荷停止', models.BooleanField(default=False, null=True)),
                ('TAT', models.CharField(blank=True, max_length=255)),
                ('案件名', models.CharField(max_length=255)),
                ('機種名型番', models.CharField(max_length=255)),
                ('進捗状況', models.TextField(blank=True, null=True)),
                ('発生日', models.DateField(blank=True, null=True)),
                ('不良症状内容', models.TextField(blank=True, null=True)),
                ('保留対象', models.PositiveBigIntegerField(blank=True, default=0)),
                ('依頼日', models.DateField(blank=True, null=True)),
                ('停止日', models.DateField(blank=True, null=True)),
                ('解除日', models.DateField(blank=True, null=True)),
                ('単品在庫', models.PositiveBigIntegerField(blank=True, default=0)),
                ('半製品在庫', models.PositiveBigIntegerField(blank=True, default=0)),
                ('完成品在庫', models.PositiveBigIntegerField(blank=True, default=0)),
                ('外部在庫', models.PositiveBigIntegerField(blank=True, default=0)),
                ('対応内容', models.TextField(blank=True, null=True)),
                ('実施予定日', models.DateField(blank=True, null=True)),
                ('実施実際日', models.DateField(blank=True, null=True)),
                ('発生原因', models.TextField(blank=True, null=True)),
                ('流出原因', models.TextField(blank=True, null=True)),
                ('なぜなぜ', models.TextField(blank=True, null=True)),
                ('分析完了予定日', models.DateField(blank=True, null=True)),
                ('分析完了実際日', models.DateField(blank=True, null=True)),
                ('是正処置発生対策', models.TextField(blank=True, null=True)),
                ('是正処置流出対策', models.TextField(blank=True, null=True)),
                ('是正処置再発防止', models.TextField(blank=True, null=True)),
                ('是正完了予定日', models.DateField(blank=True, null=True)),
                ('是正完了実際日', models.DateField(blank=True, null=True)),
                ('CLOSE日', models.DateField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('分類', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mqc.divisioncategory')),
                ('実施者', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('実施部署', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mqc.department')),
                ('発生場所', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mqc.location')),
                ('製品分', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mqc.partcategory')),
                ('責任者', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='責任者', to=settings.AUTH_USER_MODEL)),
                ('責区', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mqc.responsibilitycategory')),
            ],
            options={
                'ordering': ['-発生日'],
            },
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['name'], name='location_name_idx'),
        ),
        migrations.AddIndex(
            model_name='divisioncategory',
            index=models.Index(fields=['name'], name='divisionCategory_name_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['name'], name='department_name_idx'),
        ),
        migrations.AddIndex(
            model_name='majorqualitycase',
            index=models.Index(fields=['発生日'], name='mqc_majorqu_発生日_17e28f_idx'),
        ),
        migrations.AddIndex(
            model_name='majorqualitycase',
            index=models.Index(fields=['分類'], name='mqc_majorqu_分類_id_e06bac_idx'),
        ),
        migrations.AddIndex(
            model_name='majorqualitycase',
            index=models.Index(fields=['製品分'], name='mqc_majorqu_製品分_id_f424e8_idx'),
        ),
        migrations.AddIndex(
            model_name='majorqualitycase',
            index=models.Index(fields=['責区'], name='mqc_majorqu_責区_id_f5f549_idx'),
        ),
        migrations.AddIndex(
            model_name='majorqualitycase',
            index=models.Index(fields=['実施部署'], name='mqc_majorqu_実施部署_id_76173b_idx'),
        ),
        migrations.AddIndex(
            model_name='majorqualitycase',
            index=models.Index(fields=['発生場所'], name='mqc_majorqu_発生場所_id_3c6c3c_idx'),
        ),
    ]
